# Site settings
title: timodwhit
email: timodwhit@gmail.com
description: "Tim Whitney is a Drupal Web Dev who supposed open standards and a healthy relationship with languages."
baseurl: ""
url: "http://timodwh.it"
twitter_username: timodwhit
github_username:  timodwhit

# Build settings
markdown: kramdown
permalink: pretty
