# Site settings
title: timodwhit
email: tim.d.whitney@gmail.com
description: "Tim Whitney (timodwhit) is a drupal web developer based out of Denver, CO"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: timodwhit
github_username:  timodwhit

# Build settings
markdown: kramdown
permalink: /:categories/:title
